# Generated by Django 4.0.3 on 2022-04-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameUpdator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bridge.game')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpdator',
            fields=[
                ('gameupdator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bridge.gameupdator')),
                ('path_to_file', models.CharField(max_length=512)),
                ('run_params', models.CharField(max_length=512)),
            ],
            bases=('bridge.gameupdator',),
        ),
        migrations.CreateModel(
            name='SteamUpdator',
            fields=[
                ('gameupdator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bridge.gameupdator')),
                ('steam_path', models.CharField(max_length=512)),
            ],
            bases=('bridge.gameupdator',),
        ),
    ]
